name: Deploy GitHub Pages

on:
  workflow_dispatch: # Allows manual trigger from GitHub Actions UI

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync site files to public folder
        run: |
          mkdir public
          rsync -av --exclude='.github' --exclude='node_modules' . public/

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
